feat: accessibility enhancements in list components
appbaseio/reactivesearch pull request #1041
Opened 2019-07-10 10:47 UTC by jyash97

2019-07-10 15:34 UTC, bietkul requested changes
I can see a lot of code duplication when computing the conditions.
It'll be better if can refactor it out.

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/MultiDataList.js
> +								aria-selected={!!this.state.currentValue[selectAllLabel]}
We should avoid code duplication, Can you keep a variable to store `!!this.state.currentValue[selectAllLabel]`, and use it further.

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/MultiDataList.js
> +									aria-selected={!!this.state.currentValue[item.label]}
same goes for it.

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/MultiDataList.js
> +										name={`${this.props.componentId}-${item.label}`}
You can use `getter` to compute the values.

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/MultiList.js
> +								aria-selected={!!this.state.currentValue[selectAllLabel]}
avoid duplication

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/MultiList.js
> +									aria-selected={!!this.state.currentValue[item.key]}
avoid duplication

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/MultiList.js
> +										name={`${this.props.componentId}-${item.key}`}
Use getter

2019-07-10 15:34 UTC, bietkul commented on packages/web/src/components/list/SingleDataList.js
> +								aria-checked={this.state.currentValue === selectAllLabel}
You can use getter here too.

2019-07-10 15:35 UTC, jyash97 commented
Sure I will do these changes.

2019-07-24 11:17 UTC, bietkul requested changes

2019-07-24 11:17 UTC, bietkul commented on packages/web/src/components/list/MultiDataList.js
> +
Code like that is always confusing for the reader, why you're assigning `null` to a boolean variable.

2019-07-24 11:17 UTC, bietkul commented on packages/web/src/components/list/MultiList.js
> +
Same issue is here use `false` instead of `null`

2019-08-05 09:55 UTC, merged