feat(web): handle controlled behavior of component
appbaseio/reactivesearch pull request #1111
Opened 2019-08-22 06:59 UTC by ShahAnuj2610

fixes #1091

2019-08-22 07:06 UTC, bietkul commented
@ShahAnuj2610 You are missing range components.

2019-08-23 05:10 UTC, bietkul requested changes
I think the current implementation is not correct.
When the user defines the `value` with `onChange` then it is the user's responsibility to update the value prop accordingly.
It depends on the user whether he wants to update value or not.
Currently, you're just supplying the value to `onChange` after triggering the query i.e using `setValue`.

2019-08-23 05:10 UTC, bietkul commented on packages/web/src/components/list/MultiDataList.js
> +			this.setValue(currentValue);
@ShahAnuj2610 Why did you add `setValue` here?

2019-08-23 05:10 UTC, bietkul commented on packages/web/src/components/list/MultiDropdownList.js
> +			onChange(Object.keys(this.state.currentValue));
The same issue is here.

2019-08-23 05:10 UTC, bietkul commented on packages/web/src/components/list/MultiList.js
> +			onChange(Object.keys(this.state.currentValue));
The same issue is here.

2019-08-23 05:10 UTC, bietkul commented on packages/web/src/components/range/MultiDropdownRange.js
> +			this.selectItem({
We don't need to create any side effect when controlled behavior is being used, Just pass the value to the `onChange`.

2019-08-23 06:54 UTC, ShahAnuj2610 commented
> I think the current implementation is not correct.
> When the user defines the `value` with `onChange` then it is the user's responsibility to update the value prop accordingly.
> It depends on the user whether he wants to update value or not.
> Currently, you're just supplying the value to `onChange` after triggering the query i.e using `setValue`.

@bietkul refactoring done

2019-08-23 07:07 UTC, jyash97 requested changes
@ShahAnuj2610  Can we avoid using Controlled Component in Examples as they are directly linked to docs via Codesandbox Embed links.

2019-08-23 07:16 UTC, ShahAnuj2610 commented
> @ShahAnuj2610 Can we avoid using Controlled Component in Examples as they are directly linked to docs via Codesandbox Embed links.

Since there is a behavioral change in the `onChange` method, shouldn't we include an example, just so the user is aware?

2019-08-23 07:54 UTC, bietkul commented
I agree we should create different examples for controlled components.
For example, we already have `DataSearchControlled` example for `DataSearch`.

2019-08-23 08:45 UTC, ShahAnuj2610 commented
> I agree we should create different examples for controlled components.
> For example, we already have `DataSearchControlled` example for `DataSearch`.

examples added for controlled components

2019-08-26 05:58 UTC, bietkul requested changes

2019-08-26 05:58 UTC, bietkul commented on packages/web/src/components/list/MultiDataList.js
> +			else newValue.push(currentValue);
Put this whole logic in some util function, please avoid code duplication.

2019-08-26 09:17 UTC, bietkul approved these changes

2019-08-26 09:18 UTC, merged