Update web-CategorySearch: More than 2 suggested categories in categorySearch
appbaseio/reactivesearch pull request #1183
Opened 2019-10-03 05:44 UTC by kvin97

fix #814

2019-10-03 15:36 UTC, jyash97 commented on packages/web/src/components/search/CategorySearch.js
> +			const categorySuggestions = [];
How about slicing the array of `filteredCategories` and then mapping over it. Something like this: 

```
const size = filteredCategories.length < categorySuggestionsListSize ?  filteredCategories.length  : categorySuggestionsListSize;
const categoriesToDisplay = filteredCatogories.slice(0, size).map((item) => {
   // push to array ( try using spread operator if possible )
});
```

2019-10-03 15:36 UTC, jyash97 commented on packages/web/src/components/search/CategorySearch.js
> +			const categorySuggestions = [];
Also please try to test it locally rigorously.

2019-10-03 15:37 UTC, jyash97 commented
Can you also follow the PR template? They are present for a reason so that we don't miss documentation or other things related to PR.

2019-10-08 10:58 UTC, bietkul commented
@jyash97 Can you review it?

2019-10-08 11:10 UTC, jyash97 commented on packages/web/src/components/search/CategorySearch.js
> +										// eslint-disable-next-line react/jsx-indent
I think we wont need to disable eslint. Any reason for this ?

2019-10-08 11:29 UTC, jyash97 requested changes
LGTM 💯 

The only change we need is to revert eslint changes and the prop value will be a maximum of 10. We cant have more than that. You will need to change Prop type

2019-10-13 03:07 UTC, kvin97 commented
I found the following error with the removal of disable eslint.
![fix1](https://user-images.githubusercontent.com/53901190/66710355-2b5d7a80-ed94-11e9-88bc-b007cc1a7998.png)
Once I fixed it, following lint errors popped up.
![fix2](https://user-images.githubusercontent.com/53901190/66710363-68297180-ed94-11e9-887a-399eeda6cc52.png)
I found similar kind of issue here.
https://github.com/yannickcr/eslint-plugin-react/issues/1679

2019-10-13 03:11 UTC, kvin97 commented
> LGTM 
> 
> The only change we need is to revert eslint changes and the prop value will be a maximum of 10. We cant have more than that. You will need to change Prop type

2019-10-13 03:54 UTC, kvin97 commented
shall I use the following propType to specify the range, by importing PropTypes as `prop-types`.
`categorySuggestionsListSize: PropTypes.oneOf([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),`

2019-10-14 08:03 UTC, jyash97 commented
I think there is some eslint config issue on your side as I tried changing things on the same file and could not replicate. 

Also for `propTypes` you may need to define a custom prop type.

2019-10-20 10:00 UTC, kvin97 commented
To remove the eslint issue I revert back to a previous commit and move the code changes again. 
For `propTypes` custom prop type was defined.

2023-03-17 10:45 UTC, closed without merging