feat(vue): add controlled behavior for list components
appbaseio/reactivesearch pull request #1193
Opened 2019-10-08 16:20 UTC by jyash97

- [ ]  Add Docs

2019-10-11 04:42 UTC, bietkul requested changes
@jyash97 I have some questions:
1. I can't see `defaultValue` implemented.
2. What is the purpose of not removing the  `defaultSelected` prop?

Make these changes [here](https://github.com/appbaseio/reactivesearch/pull/1194/files) too.

2019-10-14 07:51 UTC, jyash97 commented
@bietkul I havent changed the functioning of `defaultSelected`. In this PR and the other PR I have just added support for controlled component. For `defaultValue`  we just need to do a rename and test if everything works properly which can be a separate PR I guess.

2019-10-14 09:44 UTC, bietkul commented
@jyash97 Although we can remove the `defaultSelected` prop later but The `defaultValue` prop is the part of controlled behavior, you should include that in this PR.
So do these changes:
1. Implement `defaultValue`.
2. Mark `defaultSelected` as deprecated & throw a warning if used.

2019-10-21 12:45 UTC, bietkul requested changes
@jyash97 Please check the comments, the same issues are present in multiple files.
Also, update [this](https://github.com/appbaseio/reactivesearch/pull/1194/files) PR.

2019-10-21 12:45 UTC, bietkul commented on packages/vue/src/components/list/MultiDropdownList.jsx
> +			console.warn("defaultSelected prop will be deprecated in the next release. Please replace it with defaultValue before upgrading to the next major version.");
This warning message gets repeated in many places, @jyash97 can you put it out at in some util method.

2019-10-21 12:45 UTC, bietkul commented on packages/vue/src/components/list/MultiDropdownList.jsx
> +				if (value && value.length) {
Why there is a length check?
Are you trying to make sure that the value is an `Array`?
If yes then use `Array.isArray()` instead.

2019-10-21 12:45 UTC, bietkul commented on packages/vue/src/components/list/MultiDropdownList.jsx
> +			this.setValue(newVal, true);
Use `isEqual` to compare the values.

2019-10-21 12:45 UTC, bietkul commented on packages/vue/src/components/list/SingleDropdownList.jsx
> +		value(newVal) {
Check the above comments.

2019-10-21 12:45 UTC, bietkul commented on packages/vue/src/components/list/MultiList.jsx
> +				if (value && value.length) {
Check the above comments.

2019-10-21 12:45 UTC, bietkul commented on packages/vue/src/components/list/SingleList.jsx
> +		value(newVal) {
Check the above comments.

2019-10-24 11:05 UTC, bietkul approved these changes

2019-10-24 11:05 UTC, merged