Changed the event names from camelCase to kebab-case
appbaseio/reactivesearch pull request #1584
Opened 2021-01-06 15:54 UTC by royduin

As of: https://vuejs.org/v2/guide/components-custom-events.html#Event-Names, event names should be kebab-case. Got issues with this with DOM templates.

2021-01-07 07:52 UTC, bietkul approved these changes
lgtm :+1:

2021-01-25 07:17 UTC, bietkul requested changes
@royduin This PR would break the events for existing users.
We should make that change with backward compatibility by emitting the events for both cases (kebab-case and camelCase). 
In v2.0 we'll remove the camelCase events.

2021-01-25 20:47 UTC, royduin commented
I've re-added them 👍🏻

2021-01-27 19:15 UTC, bietkul requested changes
@royduin A minor change is needed. The rest of the changes look good to me.

2021-01-27 19:15 UTC, bietkul commented on packages/vue/src/components/basic/DownShift.jsx
> +					? this.$emit(`${key}Change`, stateToSet[key]) && this.$emit(`${key}-change`, stateToSet[key])
@royduin Can we remove `&&` operator and use `if else` condition to trigger events?

2021-01-27 20:45 UTC, bietkul commented
I'm merging it so it can be out in today's version.

2021-01-27 20:45 UTC, merged

2021-01-28 07:58 UTC, royduin commented
Thanks you! 💯