fix: web #1555 RangeSlider - inappropriate role for element
appbaseio/reactivesearch pull request #1585
Opened 2021-01-11 14:51 UTC by anik-ghosh-au7

Issue Type - Bug (#1555)
Platform - Web
Description - The SliderHandle component used by rheostat returns a button component ARIA role slider which was not allowed, so changed it to div instead.
![Axe Analysis](https://user-images.githubusercontent.com/59804102/104196922-6395b200-544a-11eb-890e-2a5df6e66444.png)

2021-01-11 14:58 UTC, bietkul commented
@anik-ghosh-au7 Add a loom video to demonstrate the fix.

2021-01-11 16:05 UTC, anik-ghosh-au7 commented
https://www.loom.com/share/28d90e9e0e1f4e42baef1576e1900f72

2021-01-25 07:05 UTC, bietkul requested changes
@anik-ghosh-au7 The changes you have made can break UI for existing users who are using custom CSS on the `button` tag. Can we make that fix without breaking it?

2021-02-11 06:46 UTC, bietkul commented
@anik-ghosh-au7 Any update on this?

2023-01-27 09:16 UTC, merged