Button instead of anchor
appbaseio/reactivesearch pull request #1646
Opened 2021-04-01 10:01 UTC by royduin

As anchors do have/support a `disabled` attribute and they don't have a `href` so it doesn't make much sense to use anchors over buttons.

2021-04-09 10:38 UTC, bietkul requested changes
@royduin Can you please share a demo for this? Would it not be a breaking change for existing users?

2021-04-20 08:34 UTC, royduin commented
I'm a little busy but I'm coming back on this soon!

2021-05-25 08:01 UTC, royduin commented
![image](https://user-images.githubusercontent.com/1703233/119459853-5d8bd800-bd3e-11eb-9895-ae7cdb7bba71.png)

Nothing changes and everything just works as with anchors but with real support for the `disabled` attribute. Running into issues with anchors as the CSS selector `a:disabled` doesn't work as anchors do not have a `disabled` attribute. `button:disabled` works. And why use an anchor when there is no `href`?

2022-09-30 11:23 UTC, bietkul approved these changes

2022-09-30 11:23 UTC, merged