feat(vue): pagination prev/next label props
appbaseio/reactivesearch pull request #1650
Opened 2021-04-06 13:18 UTC by royduin

Add the possibility to override the pagination prev/next button texts with props.

2021-04-09 10:31 UTC, bietkul requested changes
@royduin Can you please follow the PR template?
Docs PR is missing

2021-04-09 10:39 UTC, royduin commented
I thought let's first see if it's ok so I can create a PR to the docs afterwards. On it 👍🏻

2021-04-09 10:40 UTC, bietkul approved these changes

2021-04-10 13:08 UTC, royduin commented
Created a PR for the docs: https://github.com/appbaseio/reactivesearch/pull/1650 👍🏻

2021-04-20 08:32 UTC, merged