Feat/support focusShortcuts, autoFocus, addonBefore, addonAfter
appbaseio/reactivesearch pull request #1724
Opened 2021-06-22 04:28 UTC by mohdashraf010897

**Description** :
- Support focusShortcuts prop to focus input field using custom keyboard shortcuts.
- support autoFocus prop for the input search field.
- Support addonBefore & addonAfter (props/ slots) to render custom jsx/ HTML markup before & after the input search field.
- Support expandSuggestionsContainer prop to expand/ limit the suggestions dropdown container width to the whole input wrapper/ input field.

**Libraries Affected:**` (hotkeys-js as a direct dependency)`

-  ReactiveSearch - web : DataSearch & CategorySearch
-  ReactiveSearch - Vue : DataSearch 

[Notion Link](https://www.notion.so/appbase/Support-searchbox-focus-with-keyboard-shortcut-3010b391595d4d0495a65e99f9591f9a)

[Docs PR Link](https://github.com/appbaseio/Docs/pull/193)

[**_`NEW`_** Loom Demo: ReactiveSearch - **_web_**-  focusShortcuts with/ without combinations](https://www.loom.com/share/7daf6fb4392e497bb13243eb337ce189)

[**_`OLD`_** Loom Demo: ReactiveSearch - **_web_**-  focusShortcuts, autoFocus, addonBefore, addonAfter, expandSuggestionsContainer](https://www.loom.com/share/1d77603df8a440708d7900af1312a82d)

[**_`OLD`_** Loom Demo: ReactiveSearch - **_Vue_**-  focusShortcuts, autoFocus, addonBefore, addonAfter, expandSuggestionsContainer](https://www.loom.com/share/0861e477deff4b94a7928b82d384a837)

2021-06-22 16:27 UTC, bietkul approved these changes
lgtm 👍

2021-06-22 17:12 UTC, bietkul requested changes

2021-06-22 17:12 UTC, bietkul commented on packages/vue/src/components/search/DataSearch.jsx
> +			if (this.hotKeyCombinationsUsed) {
@mohdashraf010897 You don't need to import it dynamically. Import at the top. Fix it in `react` too. If `hot-keys` can handle the single keys then just use that and remove your custom logic to keep the bundle size minimum.

2021-06-22 17:12 UTC, bietkul commented
@mohdashraf010897 Can we support special keys like `cmd`, `ctrl`, `shift` etc?

2021-06-23 07:39 UTC, mohdashraf010897 commented
> @mohdashraf010897 Can we support special keys like `cmd`, `ctrl`, `shift` etc?

We now support modifier keys as well
https://www.loom.com/share/86319a658acd481db95fb662678375d5

2021-06-23 10:38 UTC, bietkul requested changes

2021-06-23 10:38 UTC, bietkul commented on packages/vue/src/utils/index.js
> +export function isHotkeyCombinationUsed(focusShortcuts) {
@mohdashraf010897 Remove unused methods

2021-06-23 10:38 UTC, bietkul commented on packages/vue/src/utils/index.js
> +export function isHotkeyCombination(hotkey) {
@mohdashraf010897 Remove if not used

2021-06-23 10:38 UTC, bietkul commented on packages/web/src/utils/index.js
> +export function isHotkeyCombinationUsed(focusShortcuts) {
@mohdashraf010897 remove if not used

2021-06-23 10:44 UTC, mohdashraf010897 commented on packages/web/src/utils/index.js
> +export function isHotkeyCombinationUsed(focusShortcuts) {
removed

2021-06-23 10:44 UTC, mohdashraf010897 commented on packages/vue/src/utils/index.js
> +export function isHotkeyCombination(hotkey) {
used

2021-06-23 10:45 UTC, mohdashraf010897 commented on packages/vue/src/utils/index.js
> +export function isHotkeyCombinationUsed(focusShortcuts) {
removed

2021-06-23 10:45 UTC, bietkul approved these changes

2021-06-23 13:28 UTC, bietkul requested changes
@mohdashraf010897 FocusShortcuts doesn't work in Vue at the first attempt.
There are issues with `autoFocus` when we switch stories.

2021-06-23 18:20 UTC, merged