Feat/rs mongo support
appbaseio/reactivesearch pull request #1810
Opened 2021-11-16 06:32 UTC by mohdashraf010897

**PR Type** `Feature`

**Description** 
- Add support for `mongodb` for ReactiveSearch

- [x] React
- [ ]  Vue

[🎥  Loom](#)

[Notion Link](https://www.notion.so/appbase/Reactivesearch-Mongo-DB-Support-1ef6e865b5cf4204aaae338d22afa288)

--- 
**Related PRs**
https://github.com/appbaseio/appbase-js/pull/84
https://github.com/appbaseio/reactivecore/pull/111
---

TODO: publish `appbase-js` and upgrade versions in `reactivesearch` libraries: `web` and `vue`

2021-11-22 01:42 UTC, bietkul requested changes
@mohdashraf010897 You didn't make changes for Vue?

2021-11-22 01:42 UTC, bietkul commented on packages/web/src/components/basic/ReactiveBase.js
> +			url: props.url,
```suggestion
			url: props.url && props.url.trim() !== '' ? props.url : '',
```

2021-11-22 09:46 UTC, mohdashraf010897 commented on packages/web/src/components/basic/ReactiveBase.js
> +			url: props.url,
fixed here 👉 https://github.com/appbaseio/reactivesearch/pull/1810/commits/c4f50a6a4916d59045b0d493f530e0244a1e12be

2021-11-22 09:47 UTC, mohdashraf010897 commented
> @mohdashraf010897 You didn't make changes for Vue?

Yes, once you approve for React, i would.

2021-11-22 10:19 UTC, bietkul approved these changes

2021-11-22 10:22 UTC, bietkul commented
@mohdashraf010897 Why is it not throwing `URL` nor defined error?
https://i.imgur.com/hCZUGcF.jpg

2021-11-23 06:29 UTC, bietkul approved these changes

2021-11-29 15:16 UTC, bietkul approved these changes

2021-11-29 15:17 UTC, merged