Fix/rs issues dec 2021
appbaseio/reactivesearch pull request #1826
Opened 2021-12-11 05:39 UTC by mohdashraf010897

**PR Type** `Bug Fix`

**Description** 
fixes the below-reported issues,
- https://github.com/appbaseio/reactivesearch/issues/1821
   - fixed the issue of passing the isChecked value to `renderItem` callback.
   - fixed live example breaking due to promoted result and updated to use the `renderItem` callback demonstrating the above-fixed issue.
   - **Demo** 👉 https://www.loom.com/share/b1f63ed4c6834e7bb3bdef6f058af4ef
   - **CSB(s)**
      -  https://codesandbox.io/embed/elastic-beaver-4jvem?fontsize=14&hidenavigation=1&theme=dark

- https://github.com/appbaseio/reactivesearch/issues/1815
   - updated `vue-slider-component` to **v3.2.15**.
   - Demo 👉 https://www.loom.com/share/f436c7c916484b53a21fdfc273138f41
   - **CSB(s)**
      - [RangeSlider](https://codesandbox.io/embed/heuristic-browser-6lhnr?fontsize=14&hidenavigation=1&theme=dark)
      - [DynamicRangeSlider](https://codesandbox.io/embed/zealous-einstein-kgfuq?fontsize=14&hidenavigation=1&theme=dark)

2021-12-20 13:41 UTC, bietkul requested changes
@mohdashraf010897 This PR has the following issues:
- Too many API calls on dragging the slider. It is happening in `DRS`.
- RangeSlider is not working with `RangeInput`. Clear the `SelecteFilter` and it wouldn’t update the `RangeInput` component.
- ReactiveSearch CSS doesn't seem to work. Just compare it with the stable version.
- Test it with SSR too

I would recommend you to follow the migration guide for `vue-slider` to upgrade the version.

Create a separate PR for `renderItem` issue in list components. Check for `Vue` as well.

2021-12-20 13:41 UTC, bietkul commented on packages/web/package.json
> +	"version": "3.26.1-alpha.2",
```suggestion
	"version": "3.26.1",
```

2021-12-20 13:41 UTC, bietkul commented on packages/vue/package.json
> +	"version": "1.24.3-alpha.1",
```suggestion
	"version": "1.24.3",
```

2022-01-22 09:09 UTC, mohdashraf010897 commented
fixed here https://github.com/appbaseio/reactivesearch/pull/1853

2022-01-22 09:09 UTC, closed without merging