Feat/rs vue searchbox
appbaseio/reactivesearch pull request #1842
Opened 2022-01-12 04:45 UTC by mohdashraf010897

**PR Type** For ReactiveSearch, we will create a Searchbox component in ReactiveSearch instead of modifying the existing DataSearch component.

- [x]  Searchbox support in Vue

[🎥  Loom Vue](https://www.loom.com/share/4109b0f4e5534f3ba9e2b100bf18385f)

[Notion Link](https://www.notion.so/appbase/8648760a66da4dcfa5ebcefd2e439ddc)

[Docs PR Link ](#)

**Related PR(s)**
- https://github.com/appbaseio/playground/pull/#
- https://github.com/appbaseio/reactivecore/pull/#

2022-02-06 06:57 UTC, mohdashraf010897 commented
https://www.loom.com/share/b0d77f046648473795b17f2d93effe3a

2022-04-06 06:20 UTC, bietkul approved these changes

2022-04-06 06:20 UTC, bietkul commented on packages/vue/package.json
> +	"version": "1.27.0-gamma.2",
```suggestion
	"version": "1.27.0",
```

2022-04-06 07:17 UTC, bietkul requested changes
@mohdashraf010897 There are following issues:
- Two API calls on each keystroke
- Suggestions dropdown is closed when user types in Input box, as a result it doesn't show suggestions
https://www.loom.com/share/faf46bf3f0db4914841cb2243bfc8654

2022-04-12 04:32 UTC, mohdashraf010897 commented
> @mohdashraf010897 There are following issues:
> 
> * Two API calls on each keystroke
> * Suggestions dropdown is closed when user types in Input box, as a result it doesn't show suggestions
>   [https://www.loom.com/share/faf46bf3f0db4914841cb2243bfc8654![](chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/img/dark-loading-ring.svg)](https://www.loom.com/share/faf46bf3f0db4914841cb2243bfc8654)

@bietkul https://www.loom.com/share/ba527aa7fb2447938c75166cd6725110

2022-04-18 14:38 UTC, bietkul commented
@mohdashraf010897 Update the example. Remove unnecessary props and keep the example simple.

2022-04-26 09:27 UTC, bietkul approved these changes

2022-04-26 09:28 UTC, merged