feat(web): support sortOption for Reactive
appbaseio/reactivesearch pull request #1863
Opened 2022-02-06 18:19 UTC by mohdashraf010897

**Before submitting a pull request,** please make sure the following is done:

- [ ] Describe the proposed changes and how it'll improve the library experience.
- [ ] Please make sure that there are no linting errors in the code.
- [ ] Add a demo video/gif/screenshot to explain how did you test the fix.
- [ ] If it is a global change, try to add any side effects that it could have.
- [ ] Create a PR to add/update the docs (if needed) at [here](https://github.com/appbaseio/Docs).
- [ ] Create a PR to add/update the storybook (if needed) at [here](https://github.com/appbaseio/playground).

**Learn more about contributing:** [Contributing guides](https://github.com/appbaseio/reactivesearch/blob/next/.github/CONTRIBUTING.md)

2022-02-25 03:48 UTC, bietkul requested changes

2022-02-25 03:48 UTC, bietkul commented on packages/web/src/components/result/ReactiveList.js
> +			const sortOption = this.props.sortOptions[this.sortOptionIndex].label;
Add a `null` check before reading `label` key.

2022-02-25 09:54 UTC, mohdashraf010897 commented
@bietkul 
https://www.loom.com/share/ae934d6e678a4b8184dd12fe152079a1

2022-02-25 09:54 UTC, mohdashraf010897 commented on packages/web/src/components/result/ReactiveList.js
> +			const sortOption = this.props.sortOptions[this.sortOptionIndex].label;
Fixed here:  https://github.com/appbaseio/reactivesearch/pull/1863/commits/2dce811ce4202c2bad7b37632f0843b118a78dad

2022-02-26 05:48 UTC, mohdashraf010897 commented
Demo for [feat(vue): support for sortOptions](https://github.com/appbaseio/reactivesearch/pull/1863/commits/50477e641be718168034a900d235262a7811a3fc)
https://www.loom.com/share/2a22581d6caa4d928e512c435015a246

2022-02-28 03:51 UTC, bietkul approved these changes

2022-02-28 03:53 UTC, bietkul commented
@mohdashraf010897 The Vue demo that you shared doesn't reset the page on sort change.

2022-02-28 09:19 UTC, mohdashraf010897 commented
> @mohdashraf010897 The Vue demo that you shared doesn't reset the page on sort change.

Updated demo 
https://www.loom.com/share/71f665ef5de242d98ec536b36774d31c

also updated the basic example

2022-03-03 06:38 UTC, bietkul approved these changes

2022-03-03 06:38 UTC, merged