Show selected filter for numberbox
appbaseio/reactivesearch pull request #1927
Opened 2022-04-11 06:33 UTC by SavvyShah

**Before submitting a pull request,** please make sure the following is done:
- Display `NumberBox` in `SelectedFilters`
- Modifies a [previous change](https://github.com/appbaseio/reactivesearch/commit/16f6f857f066285846eda686853bd58b911b07a8#diff-050e15f8f60866b1c4b86b4bf56c3f0386dba6a78521fbdcda5bf1f113439e8eR135)
- [Loom preview](https://www.loom.com/share/ccbdd555d525478bb7405b11c4af0cdc)
- [Storybook PR](https://github.com/appbaseio/playground/pull/86)

2022-04-15 07:14 UTC, bietkul requested changes
@SavvyShah When you clear the selected value for number box, then it must reset the input value. It is a bug which should be fixed.

Basically, you would have to sync the `NumberBox` value (stored in local state) to the value in Redux store. For reference, check the implementation of `selectedValue` prop in `ToogleButton`.
https://github.com/appbaseio/reactivesearch/blob/next/packages/web/src/components/list/ToggleButton.js#L313

2022-05-03 09:51 UTC, SavvyShah commented
@bietkul I have updated the PR and the [Loom preview(updated)](https://www.loom.com/share/031eef9d40d645d0a9dff64691d8a085)

2022-05-03 10:26 UTC, SavvyShah commented
[Loom preview](https://www.loom.com/share/dd71347b25de4f70928321807e5beb77)

2022-05-04 10:42 UTC, bietkul requested changes
1. Test by setting the `URLParams` as `true`. Select a value and reload the page.
2. Test with clear all and clear actions.

2022-05-04 10:42 UTC, bietkul commented on packages/web/src/components/basic/NumberBox.js
> +		}
```suggestion
		if (this.props.selectedValue != prevProps.selectedValue) {
			this.setValue(this.props.selectedValue, this.props);
		}
```

2022-05-05 15:27 UTC, SavvyShah commented
[Loom preview](https://www.loom.com/share/24068f84bbe94babb8bc8cfcb48ed2c7)

2022-05-09 04:57 UTC, merged