Feat(web): endpoint property support
appbaseio/reactivesearch pull request #2056
Opened 2022-08-24 14:51 UTC by mohdashraf010897

**PR Type** `Feature`

**Description** The PR adds endpoint property support ReactiveSearch components.

[📔  Notion](https://www.notion.so/appbase/endpoint-property-support-in-RS-acd0540c4a274b99b2b454540ec210ba)

https://github.com/appbaseio/reactivecore/pull/136

2022-08-30 08:08 UTC, bietkul requested changes
@mohdashraf010897 PR looks good 👍.
Can you also share the demos with SSR for Vue and React?

2022-08-31 14:20 UTC, mohdashraf010897 commented
> @mohdashraf010897 PR looks good 👍. Can you also share the demos with SSR for Vue and React?

https://www.loom.com/share/f6ec79f0fc1b438ca15b38f010b543e1

2022-09-02 07:09 UTC, bietkul requested changes

2022-09-02 07:09 UTC, bietkul commented on packages/vue/examples/with-ssr/nuxt.config.js
> +	debug: true,
```suggestion
```

2022-09-02 07:09 UTC, bietkul commented on packages/vue/package.json
> +		"appbase-js": "^5.1.0-alpha.3",
```suggestion
		"appbase-js": "^5.0.0",
```

2022-09-02 07:09 UTC, bietkul commented on packages/web/package.json
> +		"appbase-js": "5.1.0-alpha.3",
```suggestion
		"appbase-js": "5.0.0",
```

2022-09-02 07:09 UTC, bietkul commented on packages/vue/src/server/index.js
> +									const hitsObj = response.hits
@mohdashraf010897 This change is not required, which seems specific to your endpoint example.

2022-09-05 10:05 UTC, bietkul requested changes

2022-09-05 10:05 UTC, bietkul commented on packages/web/src/server/index.js
> +		if (settings.enableAppbase && settings.endpoint instanceof Object) {
```suggestion
		if (settings.enableAppbase && settings.endpoint && settings.endpoint instanceof Object) {
```

2022-09-05 10:05 UTC, merged