Feat/vue featured suggestions
appbaseio/reactivesearch pull request #2221
Opened 2023-05-21 06:59 UTC by SavvyShah

[Notion card](https://www.notion.so/reactivesearch/Vue-Featured-Suggestions-Support-9e33557bb5bb4abfb5cd8bb8e901c7b1)

Support featured suggestions in Vue Searchbox component like in React.

2023-05-24 11:16 UTC, mohdashraf010897 commented
- the search icon shouldn’t show up beside the featured suggestions if the icon isn't set from the dashboard.
- The example for featuredSuggestions is remaining

2023-05-26 05:57 UTC, mohdashraf010897 requested changes
- [x] the search icon shouldn’t show up beside the featured suggestions if the iconUrl isn't set from the dashboard.

2023-06-05 12:24 UTC, SavvyShah commented
Review change has been done. Loom is included in the comments of [notion card](https://www.notion.so/reactivesearch/Vue-Featured-Suggestions-Support-9e33557bb5bb4abfb5cd8bb8e901c7b1).

2023-06-08 11:58 UTC, SavvyShah commented
Check latest comments in notion for loom preview

2023-06-19 03:07 UTC, mohdashraf010897 requested changes
See the comments, 

Also please share a loom testing for various icon combinations, we have encountered issues with input padding in the past and thus we should make sure we are dealing with it right. You can refer to the react version for padding values.

The test icon combinations could be - 

- focusshortcuts icon + clear icon + voice search icon + search icon(left)
- focusshortcuts icon + clear icon + voice search icon + search icon(**right**)
- focusshortcuts icon + clear icon + search icon(**right**)
- focusshortcuts icon + voice search icon + search icon(**right**)
- focusshortcuts icon + voice search icon 
- focusshortcuts icon + clear icon 
- focusshortcuts icon + search icon(**right**)
- clear icon + voice search icon
- clear icon + voice search icon + search icon(**right**)
- clear icon + search icon(**right**)
- voice search icon + search icon(**right**)
- voice search icon
- clear icon
- focusshortcuts icon

2023-06-19 03:07 UTC, mohdashraf010897 commented on packages/vue/src/components/search/SearchBox.jsx
> +												return ()=>(<span></span>)
@SavvyShah Doesn't return `null` work here? It would help if you can specify the reason to use empty span vs null.

2023-06-19 03:07 UTC, mohdashraf010897 commented on packages/vue/src/components/search/SearchBox.jsx
> +												return ()=>(<span style={{display: 'inline-block',height: '25px', width: leaveSpaceForIcon?'25px': 0}}></span>)
@SavvyShah The formatting seems a bit off, haven't you turned on lint on your machine? I have seen this in the other PR(s) as well.

2023-06-19 03:07 UTC, mohdashraf010897 commented on packages/vue/src/components/search/SearchBox.jsx
> +				let shortcut = this.$props.focusShortcuts[0];
@SavvyShah Is this conversion also followed in React version?

2023-06-19 18:29 UTC, SavvyShah commented on packages/vue/src/components/search/SearchBox.jsx
> +												return ()=>(<span></span>)
The code in comment looks like below now.
```jsx
return () => (
	<span
		style={{
			display: 'inline-block',
			height: '25px',
			width: leaveSpaceForIcon ? '25px' : 0,
		}}
	></span>
);
```

2023-06-19 18:30 UTC, SavvyShah commented on packages/vue/src/components/search/SearchBox.jsx
> +												return ()=>(<span style={{display: 'inline-block',height: '25px', width: leaveSpaceForIcon?'25px': 0}}></span>)
The above comment is the same. 
```jsx
return () => (
	<span
		style={{
			display: 'inline-block',
			height: '25px',
			width: leaveSpaceForIcon ? '25px' : 0,
		}}
	></span>
);
```

2023-06-19 18:30 UTC, SavvyShah commented on packages/vue/src/components/search/SearchBox.jsx
> +				let shortcut = this.$props.focusShortcuts[0];
Yes.

2023-06-23 03:16 UTC, mohdashraf010897 approved these changes

2023-06-23 03:17 UTC, merged