Make Tileserver customizable from props
appbaseio/reactivesearch pull request #811
Opened 2019-01-31 10:32 UTC by mkaraula

IWLT propose an additional prop for ReactiveOpenStreetMap do change the tile server if needed. If the prop is not set ReactiveOpenStreetMap will default to `http://{s}.tile.osm.org/{z}/{x}/{y}.png`

2019-01-31 13:23 UTC, lakhansamani commented on packages/maps/src/components/result/ReactiveOpenStreetMap.js
> +				<OpenStreetLayer url={this.props.tileServer ? this.props.tileServer : 'http://{s}.tile.osm.org/{z}/{x}/{y}.png'} />
This can be written as
<OpenStreetLayer url={this.props.tileServer || 'https://{s}.tile.osm.org/{z}/{x}/{y}.png'} />

2019-02-01 11:37 UTC, metagrover approved these changes

2019-02-01 11:39 UTC, metagrover requested changes
Looks good 👌 

One quick modification - we will need to add `tileServer` prop to this component's `propTypes` as well.

2019-02-01 12:44 UTC, mkaraula commented
Hey @metagrover, where can I find the Prop Types for this component? I was a bit lost ahily looking for it 😅

2019-02-01 12:50 UTC, metagrover commented
Since we use `ReactiveMap` as the base component for `ReactiveOpenStreetMap`, we don't have additional props (hence propTypes) in this component. So, you can add it as:

```js
// import types:
import types from '@appbaseio/reactivecore/lib/utils/types';

// add proptypes:
ReactiveOpenStreetMap.propTypes = {
    tileServer: types.string,
};
```

in this file.

2019-02-04 13:23 UTC, metagrover approved these changes

2019-02-04 13:26 UTC, merged